/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.assignment;

import java.util.concurrent.Executors;

import org.jsoup.nodes.Document;

public class App {
    public static void main(String[] args) {
        UserInput userInput = UserInput.getUserInput();

        WebCrawler webCrawler = new WebCrawler(
                Executors.newCachedThreadPool(),
                userInput.getUrl(),
                userInput.getDepth());

        Document htmlReport = webCrawler.getHtmlReport();

        HeaderTranslator headerTranslator = new HeaderTranslator(htmlReport);

        MarkdownConverter mdConverter = new MarkdownConverter(
                headerTranslator.translateHeadersInDoc(
                        UserInput.getUserInput().getTargetLanguage()));

        FileWriter.writeToFile(mdConverter.convertDocument(), "report.md");

        ErrorLogger.getErrorLogger().writeErrorLogToFile();
    }
}
