/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.assignment;

import org.jsoup.nodes.Document;

public class App {
    public static void main(String[] args) {
        UserInput userInput = UserInput.getUserInput();
        Document htmlReport = new ConcurrentCrawler().generateHtmlReport(userInput.getUrls(), userInput.getDepth());
        htmlReport = new HeaderTranslator(htmlReport).translateHeadersInDoc(userInput.getTargetLanguage());
        String mdReport = new MarkdownConverter(htmlReport).convertDocument();
        FileWriter.writeToFile(mdReport, "report.md");
    }
}
