/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cc.assignment_1;

public class App {
    public static void main(String[] args) {
        UserInput userInput = UserInput.getUserInput();
    }
}
